### ISSUE TITLE
Failed to bind one of the listener ports.

### ISSUE THREAD

**Issue by gordon4067** [yudazilian/Sneak#1]
I tried to run test.py with "python3 test.py" and I got 'EEEEEE'. All error message shows below

ERROR: test_renew_identity (__main__.TestSession)
test_renew_identity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sneak/test.py", line 38, in test_renew_identity
    s = Session()
  File "/home/USERNAME/Downloads/Sneak-master/sneak/Http.py", line 178, in __init__
    self.run_proxy(socks_port, control_port, proxy_host, exit_country_code, tor_path)
  File "/home/gordon/Downloads/Sneak-master/sneak/Http.py", line 104, in run_proxy
    self.proxy.run()
  File "/home/USERNAME/Downloads/Sneak-master/sneak/Tor.py", line 95, in run
    init_msg_handler=print_bootstrap_lines
  File "/home/gordon/.local/lib/python3.5/site-packages/stem/process.py", line 274, in launch_tor_with_config
    return launch_tor(tor_cmd, ['-f', '-'], None, completion_percent, init_msg_handler, timeout, take_ownership, stdin = config_str)
  File "/home/USERNAME/.local/lib/python3.5/site-packages/stem/process.py", line 153, in launch_tor
    raise OSError('Process terminated: %s' % last_problem)
OSError: Process terminated: Failed to bind one of the listener ports.

It seems that I did't open tor-browser successfully but when I check 'netstat -anlp | grep :9050'.
I got   'tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN'

**Comment by 0xyd** [comment]
The main problem is that once the test code is failed, the testing thread leaves which make Tor proxy still open. Therefore, we have to kill it manually through kill command.

**Comment by rapttor** [comment]
Actually this sometimes is related to the daemon process, so check:

`nano /etc/default/tor`

line 
RUN_DAEMON="yes" 
should be "no"

stop/restart tor:

`sudo /etc/init.d/tor stop`
